services:
    david63.resetlogin.admin.controller:
        class: david63\resetlogin\controller\admin_controller
        arguments:
            - '@config'
            - '@dbal.conn'
            - '@request'
            - '@template'
            - '@user'
            - '@log'
            - '%core.root_path%'
            - '%core.php_ext%'
            - '@language'			
